import type { Metadata } from "next";
import { Providers } from "../providers/Providers";
import { Container } from "@chakra-ui/react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <Providers>
          <Container maxW="container.lg" m="0 auto" centerContent>
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  );
}
